using System;

namespace JavaNet.Jvm.Parser.Methods
{
    /// <summary>
    /// Enum flags representing access flags of fields.
    /// </summary>
    [Flags]
    public enum JavaMethodAccessFlags
    {
        /// <summary>
        /// The public keyword.
        /// </summary>
        Public = 0x0001,

        /// <summary>
        /// The private keyword.
        /// </summary>
        Private = 0x0002,

        /// <summary>
        /// The protected keyword.
        /// </summary>
        Protected = 0x0004,

        /// <summary>
        /// The static keyword.
        /// </summary>
        Static = 0x0008,

        /// <summary>
        /// The final keyword.
        /// </summary>
        Final = 0x0010,

        /// <summary>
        /// The synchronized keyword.
        /// </summary>
        Synchronized = 0x0020,

        /// <summary>
        /// Indicates a bridge method generated by the compiler.
        /// </summary>
        Bridge = 0x0040,

        /// <summary>
        /// Indicates the class has a variable number of arguments.
        /// </summary>
        VariableArguments = 0x0080,

        /// <summary>
        /// The native keyword.
        /// </summary>
        Native = 0x0100,

        /// <summary>
        /// The abstract keyword.
        /// </summary>
        Abstract = 0x0400,

        /// <summary>
        /// The strictfp keyword.
        /// </summary>
        Strict = 0x0800,

        /// <summary>
        /// Indicates a synthetic method.
        /// </summary>
        Synthetic = 0x1000
    }
}
